// <auto-generated />
namespace Mvc4EF5.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ColumnFirstName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColumnFirstName));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280726210_ColumnFirstName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
